version: '3.5'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: review-service-container
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/br
    depends_on:
      - db
    ports:
      - "127.0.0.1:8082:8082"
    networks:
      - product-review-network

  db:
    image: 'postgres:13.1'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "127.0.0.1:5433:5432"
    networks:
      - product-review-network

networks:
  product-review-network:
    name: product-review-network
    driver: bridge